spring.application.name=auth-service

server.port=8090

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# JWT signing (shared secret; must match gateway + services)
app.jwt.issuer=hospital-auth
app.jwt.ttl-seconds=3600
# IMPORTANT: change this in real usage
app.jwt.secret=change-me-to-a-long-random-secret-value

# Demo user credentials (replace with DB later)
app.auth.username=admin
app.auth.password=admin123
